### ISSUE TITLE
Is this app alive?

### ISSUE THREAD

**Issue by DarkDirectX** [andrewarrow/boring_company_chat#2]
Hello. Is this project still alive or deprecated? 
I want to contribute too. Default Slack app based on electron is soooooo slow, so we need native app.

**Comment by andrewarrow** [comment]
deprecated. I was very much into it before slack changed the rules and made each slack network admin approve this app before you can get your access token. So I can only use it on like my personal slack network not my official work one. But I think the code is great. If you want to take it and run with it, by all means. Happy to answer any questions.

**Comment by DarkDirectX** [comment]
Sadly.
